// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: folders.sql

package db

import (
	"context"
	"database/sql"
)

const checkFolderExists = `-- name: CheckFolderExists :one
SELECT COUNT(*) as count FROM folders
WHERE id = ? AND user_id = ?
`

type CheckFolderExistsParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) CheckFolderExists(ctx context.Context, arg CheckFolderExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkFolderExists, arg.ID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProjectsInFolder = `-- name: CountProjectsInFolder :one
SELECT COUNT(*) as count FROM projects
WHERE folder_id = ?
`

func (q *Queries) CountProjectsInFolder(ctx context.Context, folderID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjectsInFolder, folderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSubfoldersInFolder = `-- name: CountSubfoldersInFolder :one
SELECT COUNT(*) as count FROM folders
WHERE parent_id = ?
`

func (q *Queries) CountSubfoldersInFolder(ctx context.Context, parentID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSubfoldersInFolder, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFolder = `-- name: CreateFolder :one
INSERT INTO folders (user_id, parent_id, name, folder_order)
VALUES (?, ?, ?, ?)
RETURNING id, user_id, parent_id, name, folder_order, created_at, updated_at
`

type CreateFolderParams struct {
	UserID      int64         `json:"user_id"`
	ParentID    sql.NullInt64 `json:"parent_id"`
	Name        string        `json:"name"`
	FolderOrder int64         `json:"folder_order"`
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRowContext(ctx, createFolder,
		arg.UserID,
		arg.ParentID,
		arg.Name,
		arg.FolderOrder,
	)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.FolderOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFolder = `-- name: DeleteFolder :exec
DELETE FROM folders
WHERE id = ? AND user_id = ?
`

type DeleteFolderParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteFolder(ctx context.Context, arg DeleteFolderParams) error {
	_, err := q.db.ExecContext(ctx, deleteFolder, arg.ID, arg.UserID)
	return err
}

const deleteFolderByID = `-- name: DeleteFolderByID :exec
DELETE FROM folders
WHERE id = ?
`

func (q *Queries) DeleteFolderByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFolderByID, id)
	return err
}

const getFolder = `-- name: GetFolder :one
SELECT id, user_id, parent_id, name, folder_order, created_at, updated_at FROM folders
WHERE id = ? AND user_id = ?
`

type GetFolderParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetFolder(ctx context.Context, arg GetFolderParams) (Folder, error) {
	row := q.db.QueryRowContext(ctx, getFolder, arg.ID, arg.UserID)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.FolderOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFolderByID = `-- name: GetFolderByID :one
SELECT id, user_id, parent_id, name, folder_order, created_at, updated_at FROM folders
WHERE id = ?
`

func (q *Queries) GetFolderByID(ctx context.Context, id int64) (Folder, error) {
	row := q.db.QueryRowContext(ctx, getFolderByID, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.FolderOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllFoldersByUser = `-- name: ListAllFoldersByUser :many
SELECT id, user_id, parent_id, name, folder_order, created_at, updated_at FROM folders
WHERE user_id = ?
ORDER BY folder_order ASC, created_at DESC
`

func (q *Queries) ListAllFoldersByUser(ctx context.Context, userID int64) ([]Folder, error) {
	rows, err := q.db.QueryContext(ctx, listAllFoldersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.FolderOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFoldersByParent = `-- name: ListFoldersByParent :many
SELECT id, user_id, parent_id, name, folder_order, created_at, updated_at FROM folders
WHERE user_id = ? AND parent_id = ?
ORDER BY folder_order ASC, created_at DESC
`

type ListFoldersByParentParams struct {
	UserID   int64         `json:"user_id"`
	ParentID sql.NullInt64 `json:"parent_id"`
}

func (q *Queries) ListFoldersByParent(ctx context.Context, arg ListFoldersByParentParams) ([]Folder, error) {
	rows, err := q.db.QueryContext(ctx, listFoldersByParent, arg.UserID, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.FolderOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFoldersByUser = `-- name: ListFoldersByUser :many
SELECT id, user_id, parent_id, name, folder_order, created_at, updated_at FROM folders
WHERE user_id = ? AND parent_id IS NULL
ORDER BY folder_order ASC, created_at DESC
`

func (q *Queries) ListFoldersByUser(ctx context.Context, userID int64) ([]Folder, error) {
	rows, err := q.db.QueryContext(ctx, listFoldersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.FolderOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsInFolder = `-- name: ListProjectsInFolder :many
SELECT
    p.id, p.user_id, p.name, p.description, p.quality_override, p.created_at, p.updated_at, p.public_id, p.cover_art_path, p.cover_art_mime, p.cover_art_updated_at, p.author_override, p.folder_id, p.folder_added_at, p.notes, p.notes_author_name, p.notes_updated_at, p.visibility_status, p.allow_editing, p.allow_downloads, p.password_hash, p.origin_instance_url, p.shared_with_instance_users, p.custom_order, p.cover_processed,
    u.username as owner_username
FROM projects p
JOIN users u ON p.user_id = u.id
WHERE p.folder_id = ? AND p.user_id = ?
ORDER BY p.folder_added_at ASC
`

type ListProjectsInFolderParams struct {
	FolderID sql.NullInt64 `json:"folder_id"`
	UserID   int64         `json:"user_id"`
}

type ListProjectsInFolderRow struct {
	ID                      int64          `json:"id"`
	UserID                  int64          `json:"user_id"`
	Name                    string         `json:"name"`
	Description             sql.NullString `json:"description"`
	QualityOverride         sql.NullString `json:"quality_override"`
	CreatedAt               sql.NullTime   `json:"created_at"`
	UpdatedAt               sql.NullTime   `json:"updated_at"`
	PublicID                string         `json:"public_id"`
	CoverArtPath            sql.NullString `json:"cover_art_path"`
	CoverArtMime            sql.NullString `json:"cover_art_mime"`
	CoverArtUpdatedAt       sql.NullTime   `json:"cover_art_updated_at"`
	AuthorOverride          sql.NullString `json:"author_override"`
	FolderID                sql.NullInt64  `json:"folder_id"`
	FolderAddedAt           sql.NullTime   `json:"folder_added_at"`
	Notes                   sql.NullString `json:"notes"`
	NotesAuthorName         sql.NullString `json:"notes_author_name"`
	NotesUpdatedAt          sql.NullTime   `json:"notes_updated_at"`
	VisibilityStatus        string         `json:"visibility_status"`
	AllowEditing            bool           `json:"allow_editing"`
	AllowDownloads          bool           `json:"allow_downloads"`
	PasswordHash            sql.NullString `json:"password_hash"`
	OriginInstanceUrl       sql.NullString `json:"origin_instance_url"`
	SharedWithInstanceUsers sql.NullBool   `json:"shared_with_instance_users"`
	CustomOrder             int64          `json:"custom_order"`
	CoverProcessed          sql.NullBool   `json:"cover_processed"`
	OwnerUsername           string         `json:"owner_username"`
}

func (q *Queries) ListProjectsInFolder(ctx context.Context, arg ListProjectsInFolderParams) ([]ListProjectsInFolderRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsInFolder, arg.FolderID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsInFolderRow{}
	for rows.Next() {
		var i ListProjectsInFolderRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.QualityOverride,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublicID,
			&i.CoverArtPath,
			&i.CoverArtMime,
			&i.CoverArtUpdatedAt,
			&i.AuthorOverride,
			&i.FolderID,
			&i.FolderAddedAt,
			&i.Notes,
			&i.NotesAuthorName,
			&i.NotesUpdatedAt,
			&i.VisibilityStatus,
			&i.AllowEditing,
			&i.AllowDownloads,
			&i.PasswordHash,
			&i.OriginInstanceUrl,
			&i.SharedWithInstanceUsers,
			&i.CustomOrder,
			&i.CoverProcessed,
			&i.OwnerUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFolder = `-- name: UpdateFolder :one
UPDATE folders
SET name = ?, parent_id = ?, folder_order = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
RETURNING id, user_id, parent_id, name, folder_order, created_at, updated_at
`

type UpdateFolderParams struct {
	Name        string        `json:"name"`
	ParentID    sql.NullInt64 `json:"parent_id"`
	FolderOrder int64         `json:"folder_order"`
	ID          int64         `json:"id"`
	UserID      int64         `json:"user_id"`
}

func (q *Queries) UpdateFolder(ctx context.Context, arg UpdateFolderParams) (Folder, error) {
	row := q.db.QueryRowContext(ctx, updateFolder,
		arg.Name,
		arg.ParentID,
		arg.FolderOrder,
		arg.ID,
		arg.UserID,
	)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.FolderOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFolderName = `-- name: UpdateFolderName :one
UPDATE folders
SET name = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
RETURNING id, user_id, parent_id, name, folder_order, created_at, updated_at
`

type UpdateFolderNameParams struct {
	Name   string `json:"name"`
	ID     int64  `json:"id"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) UpdateFolderName(ctx context.Context, arg UpdateFolderNameParams) (Folder, error) {
	row := q.db.QueryRowContext(ctx, updateFolderName, arg.Name, arg.ID, arg.UserID)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.FolderOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFolderOrder = `-- name: UpdateFolderOrder :exec
UPDATE folders
SET folder_order = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
`

type UpdateFolderOrderParams struct {
	FolderOrder int64 `json:"folder_order"`
	ID          int64 `json:"id"`
	UserID      int64 `json:"user_id"`
}

func (q *Queries) UpdateFolderOrder(ctx context.Context, arg UpdateFolderOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateFolderOrder, arg.FolderOrder, arg.ID, arg.UserID)
	return err
}

const updateFolderParent = `-- name: UpdateFolderParent :one
UPDATE folders
SET parent_id = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
RETURNING id, user_id, parent_id, name, folder_order, created_at, updated_at
`

type UpdateFolderParentParams struct {
	ParentID sql.NullInt64 `json:"parent_id"`
	ID       int64         `json:"id"`
	UserID   int64         `json:"user_id"`
}

func (q *Queries) UpdateFolderParent(ctx context.Context, arg UpdateFolderParentParams) (Folder, error) {
	row := q.db.QueryRowContext(ctx, updateFolderParent, arg.ParentID, arg.ID, arg.UserID)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.FolderOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
