// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: instance_settings.sql

package db

import (
	"context"
	"database/sql"
)

const getInstanceSettings = `-- name: GetInstanceSettings :one
SELECT id, name, created_at, updated_at, session_invalidated_at FROM instance_settings
WHERE id = 1
`

func (q *Queries) GetInstanceSettings(ctx context.Context) (InstanceSetting, error) {
	row := q.db.QueryRowContext(ctx, getInstanceSettings)
	var i InstanceSetting
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SessionInvalidatedAt,
	)
	return i, err
}

const getSessionInvalidatedAt = `-- name: GetSessionInvalidatedAt :one
SELECT session_invalidated_at FROM instance_settings WHERE id = 1
`

func (q *Queries) GetSessionInvalidatedAt(ctx context.Context) (sql.NullTime, error) {
	row := q.db.QueryRowContext(ctx, getSessionInvalidatedAt)
	var session_invalidated_at sql.NullTime
	err := row.Scan(&session_invalidated_at)
	return session_invalidated_at, err
}

const invalidateSessions = `-- name: InvalidateSessions :exec
UPDATE instance_settings
SET session_invalidated_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = 1
`

func (q *Queries) InvalidateSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, invalidateSessions)
	return err
}

const updateInstanceName = `-- name: UpdateInstanceName :one
UPDATE instance_settings
SET name = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = 1
RETURNING id, name, created_at, updated_at, session_invalidated_at
`

func (q *Queries) UpdateInstanceName(ctx context.Context, name string) (InstanceSetting, error) {
	row := q.db.QueryRowContext(ctx, updateInstanceName, name)
	var i InstanceSetting
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SessionInvalidatedAt,
	)
	return i, err
}

const upsertInstanceSettings = `-- name: UpsertInstanceSettings :one
INSERT INTO instance_settings (id, name)
VALUES (1, ?)
ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, name, created_at, updated_at, session_invalidated_at
`

func (q *Queries) UpsertInstanceSettings(ctx context.Context, name string) (InstanceSetting, error) {
	row := q.db.QueryRowContext(ctx, upsertInstanceSettings, name)
	var i InstanceSetting
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SessionInvalidatedAt,
	)
	return i, err
}
