// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invite_tokens.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createInviteToken = `-- name: CreateInviteToken :one
INSERT INTO invite_tokens (token_hash, token_type, created_by, email, expires_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, token_hash, token_type, user_id, created_by, email, used, used_at, created_at, expires_at
`

type CreateInviteTokenParams struct {
	TokenHash string    `json:"token_hash"`
	TokenType string    `json:"token_type"`
	CreatedBy int64     `json:"created_by"`
	Email     string    `json:"email"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateInviteToken(ctx context.Context, arg CreateInviteTokenParams) (InviteToken, error) {
	row := q.db.QueryRowContext(ctx, createInviteToken,
		arg.TokenHash,
		arg.TokenType,
		arg.CreatedBy,
		arg.Email,
		arg.ExpiresAt,
	)
	var i InviteToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.TokenType,
		&i.UserID,
		&i.CreatedBy,
		&i.Email,
		&i.Used,
		&i.UsedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createResetToken = `-- name: CreateResetToken :one
INSERT INTO invite_tokens (token_hash, token_type, user_id, created_by, email, expires_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, token_hash, token_type, user_id, created_by, email, used, used_at, created_at, expires_at
`

type CreateResetTokenParams struct {
	TokenHash string        `json:"token_hash"`
	TokenType string        `json:"token_type"`
	UserID    sql.NullInt64 `json:"user_id"`
	CreatedBy int64         `json:"created_by"`
	Email     string        `json:"email"`
	ExpiresAt time.Time     `json:"expires_at"`
}

func (q *Queries) CreateResetToken(ctx context.Context, arg CreateResetTokenParams) (InviteToken, error) {
	row := q.db.QueryRowContext(ctx, createResetToken,
		arg.TokenHash,
		arg.TokenType,
		arg.UserID,
		arg.CreatedBy,
		arg.Email,
		arg.ExpiresAt,
	)
	var i InviteToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.TokenType,
		&i.UserID,
		&i.CreatedBy,
		&i.Email,
		&i.Used,
		&i.UsedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :exec
DELETE FROM invite_tokens
WHERE expires_at < CURRENT_TIMESTAMP AND used = 0
`

func (q *Queries) DeleteExpiredTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredTokens)
	return err
}

const getInviteTokenByToken = `-- name: GetInviteTokenByToken :one
SELECT id, token_hash, token_type, user_id, created_by, email, used, used_at, created_at, expires_at FROM invite_tokens
WHERE token_hash = ?
`

func (q *Queries) GetInviteTokenByToken(ctx context.Context, tokenHash string) (InviteToken, error) {
	row := q.db.QueryRowContext(ctx, getInviteTokenByToken, tokenHash)
	var i InviteToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.TokenType,
		&i.UserID,
		&i.CreatedBy,
		&i.Email,
		&i.Used,
		&i.UsedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getTokensByUser = `-- name: GetTokensByUser :many
SELECT id, token_hash, token_type, user_id, created_by, email, used, used_at, created_at, expires_at FROM invite_tokens
WHERE user_id = ? OR created_by = ?
ORDER BY created_at DESC
`

type GetTokensByUserParams struct {
	UserID    sql.NullInt64 `json:"user_id"`
	CreatedBy int64         `json:"created_by"`
}

func (q *Queries) GetTokensByUser(ctx context.Context, arg GetTokensByUserParams) ([]InviteToken, error) {
	rows, err := q.db.QueryContext(ctx, getTokensByUser, arg.UserID, arg.CreatedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InviteToken{}
	for rows.Next() {
		var i InviteToken
		if err := rows.Scan(
			&i.ID,
			&i.TokenHash,
			&i.TokenType,
			&i.UserID,
			&i.CreatedBy,
			&i.Email,
			&i.Used,
			&i.UsedAt,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserInviteTokens = `-- name: GetUserInviteTokens :many
SELECT id, token_hash, token_type, user_id, created_by, email, used, used_at, created_at, expires_at FROM invite_tokens
WHERE created_by = ? AND token_type = 'invite'
ORDER BY created_at DESC
`

func (q *Queries) GetUserInviteTokens(ctx context.Context, createdBy int64) ([]InviteToken, error) {
	rows, err := q.db.QueryContext(ctx, getUserInviteTokens, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InviteToken{}
	for rows.Next() {
		var i InviteToken
		if err := rows.Scan(
			&i.ID,
			&i.TokenHash,
			&i.TokenType,
			&i.UserID,
			&i.CreatedBy,
			&i.Email,
			&i.Used,
			&i.UsedAt,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTokenAsUsed = `-- name: MarkTokenAsUsed :one
UPDATE invite_tokens
SET used = 1, used_at = CURRENT_TIMESTAMP
WHERE id = ? AND used = 0
RETURNING id, token_hash, token_type, user_id, created_by, email, used, used_at, created_at, expires_at
`

func (q *Queries) MarkTokenAsUsed(ctx context.Context, id int64) (InviteToken, error) {
	row := q.db.QueryRowContext(ctx, markTokenAsUsed, id)
	var i InviteToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.TokenType,
		&i.UserID,
		&i.CreatedBy,
		&i.Email,
		&i.Used,
		&i.UsedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
