// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notes.sql

package db

import (
	"context"
	"database/sql"
)

const createProjectNote = `-- name: CreateProjectNote :one
INSERT INTO notes (user_id, project_id, content, author_name)
VALUES (?, ?, ?, ?)
RETURNING id, user_id, track_id, project_id, content, author_name, created_at, updated_at
`

type CreateProjectNoteParams struct {
	UserID     int64         `json:"user_id"`
	ProjectID  sql.NullInt64 `json:"project_id"`
	Content    string        `json:"content"`
	AuthorName string        `json:"author_name"`
}

func (q *Queries) CreateProjectNote(ctx context.Context, arg CreateProjectNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, createProjectNote,
		arg.UserID,
		arg.ProjectID,
		arg.Content,
		arg.AuthorName,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TrackID,
		&i.ProjectID,
		&i.Content,
		&i.AuthorName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTrackNote = `-- name: CreateTrackNote :one
INSERT INTO notes (user_id, track_id, content, author_name)
VALUES (?, ?, ?, ?)
RETURNING id, user_id, track_id, project_id, content, author_name, created_at, updated_at
`

type CreateTrackNoteParams struct {
	UserID     int64         `json:"user_id"`
	TrackID    sql.NullInt64 `json:"track_id"`
	Content    string        `json:"content"`
	AuthorName string        `json:"author_name"`
}

func (q *Queries) CreateTrackNote(ctx context.Context, arg CreateTrackNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, createTrackNote,
		arg.UserID,
		arg.TrackID,
		arg.Content,
		arg.AuthorName,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TrackID,
		&i.ProjectID,
		&i.Content,
		&i.AuthorName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM notes
WHERE id = ? AND user_id = ?
`

type DeleteNoteParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteNote(ctx context.Context, arg DeleteNoteParams) error {
	_, err := q.db.ExecContext(ctx, deleteNote, arg.ID, arg.UserID)
	return err
}

const getNotesByProject = `-- name: GetNotesByProject :many
SELECT id, user_id, track_id, project_id, content, author_name, created_at, updated_at FROM notes
WHERE project_id = ?
ORDER BY updated_at DESC
`

func (q *Queries) GetNotesByProject(ctx context.Context, projectID sql.NullInt64) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, getNotesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TrackID,
			&i.ProjectID,
			&i.Content,
			&i.AuthorName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotesByTrack = `-- name: GetNotesByTrack :many
SELECT id, user_id, track_id, project_id, content, author_name, created_at, updated_at FROM notes
WHERE track_id = ?
ORDER BY updated_at DESC
`

func (q *Queries) GetNotesByTrack(ctx context.Context, trackID sql.NullInt64) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, getNotesByTrack, trackID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TrackID,
			&i.ProjectID,
			&i.Content,
			&i.AuthorName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserNoteForProject = `-- name: GetUserNoteForProject :one
SELECT id, user_id, track_id, project_id, content, author_name, created_at, updated_at FROM notes
WHERE user_id = ? AND project_id = ?
`

type GetUserNoteForProjectParams struct {
	UserID    int64         `json:"user_id"`
	ProjectID sql.NullInt64 `json:"project_id"`
}

func (q *Queries) GetUserNoteForProject(ctx context.Context, arg GetUserNoteForProjectParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, getUserNoteForProject, arg.UserID, arg.ProjectID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TrackID,
		&i.ProjectID,
		&i.Content,
		&i.AuthorName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserNoteForTrack = `-- name: GetUserNoteForTrack :one
SELECT id, user_id, track_id, project_id, content, author_name, created_at, updated_at FROM notes
WHERE user_id = ? AND track_id = ?
`

type GetUserNoteForTrackParams struct {
	UserID  int64         `json:"user_id"`
	TrackID sql.NullInt64 `json:"track_id"`
}

func (q *Queries) GetUserNoteForTrack(ctx context.Context, arg GetUserNoteForTrackParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, getUserNoteForTrack, arg.UserID, arg.TrackID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TrackID,
		&i.ProjectID,
		&i.Content,
		&i.AuthorName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes
SET content = ?,
    author_name = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
RETURNING id, user_id, track_id, project_id, content, author_name, created_at, updated_at
`

type UpdateNoteParams struct {
	Content    string `json:"content"`
	AuthorName string `json:"author_name"`
	ID         int64  `json:"id"`
	UserID     int64  `json:"user_id"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, updateNote,
		arg.Content,
		arg.AuthorName,
		arg.ID,
		arg.UserID,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TrackID,
		&i.ProjectID,
		&i.Content,
		&i.AuthorName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProjectNote = `-- name: UpsertProjectNote :one
INSERT INTO notes (user_id, project_id, content, author_name)
VALUES (?, ?, ?, ?)
ON CONFLICT (user_id, project_id) DO UPDATE SET
    content = excluded.content,
    author_name = excluded.author_name,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, user_id, track_id, project_id, content, author_name, created_at, updated_at
`

type UpsertProjectNoteParams struct {
	UserID     int64         `json:"user_id"`
	ProjectID  sql.NullInt64 `json:"project_id"`
	Content    string        `json:"content"`
	AuthorName string        `json:"author_name"`
}

func (q *Queries) UpsertProjectNote(ctx context.Context, arg UpsertProjectNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, upsertProjectNote,
		arg.UserID,
		arg.ProjectID,
		arg.Content,
		arg.AuthorName,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TrackID,
		&i.ProjectID,
		&i.Content,
		&i.AuthorName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTrackNote = `-- name: UpsertTrackNote :one
INSERT INTO notes (user_id, track_id, content, author_name)
VALUES (?, ?, ?, ?)
ON CONFLICT (user_id, track_id) DO UPDATE SET
    content = excluded.content,
    author_name = excluded.author_name,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, user_id, track_id, project_id, content, author_name, created_at, updated_at
`

type UpsertTrackNoteParams struct {
	UserID     int64         `json:"user_id"`
	TrackID    sql.NullInt64 `json:"track_id"`
	Content    string        `json:"content"`
	AuthorName string        `json:"author_name"`
}

func (q *Queries) UpsertTrackNote(ctx context.Context, arg UpsertTrackNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, upsertTrackNote,
		arg.UserID,
		arg.TrackID,
		arg.Content,
		arg.AuthorName,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TrackID,
		&i.ProjectID,
		&i.Content,
		&i.AuthorName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
