// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package db

import (
	"context"
)

const getGlobalStorageStats = `-- name: GetGlobalStorageStats :one
SELECT
    COALESCE(SUM(tf.file_size), 0) as total_size_bytes,
    COALESCE(SUM(CASE WHEN tf.quality = 'source' THEN tf.file_size ELSE 0 END), 0) as source_size_bytes,
    COALESCE(SUM(CASE WHEN tf.quality = 'lossless' THEN tf.file_size ELSE 0 END), 0) as lossless_size_bytes,
    COALESCE(SUM(CASE WHEN tf.quality = 'lossy' THEN tf.file_size ELSE 0 END), 0) as lossy_size_bytes,
    COUNT(DISTINCT tf.id) as file_count,
    COUNT(DISTINCT t.project_id) as project_count,
    COUNT(DISTINCT t.id) as track_count
FROM track_files tf
INNER JOIN track_versions tv ON tf.version_id = tv.id
INNER JOIN tracks t ON tv.track_id = t.id
`

type GetGlobalStorageStatsRow struct {
	TotalSizeBytes    interface{} `json:"total_size_bytes"`
	SourceSizeBytes   interface{} `json:"source_size_bytes"`
	LosslessSizeBytes interface{} `json:"lossless_size_bytes"`
	LossySizeBytes    interface{} `json:"lossy_size_bytes"`
	FileCount         int64       `json:"file_count"`
	ProjectCount      int64       `json:"project_count"`
	TrackCount        int64       `json:"track_count"`
}

func (q *Queries) GetGlobalStorageStats(ctx context.Context) (GetGlobalStorageStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getGlobalStorageStats)
	var i GetGlobalStorageStatsRow
	err := row.Scan(
		&i.TotalSizeBytes,
		&i.SourceSizeBytes,
		&i.LosslessSizeBytes,
		&i.LossySizeBytes,
		&i.FileCount,
		&i.ProjectCount,
		&i.TrackCount,
	)
	return i, err
}

const getStorageStatsByUser = `-- name: GetStorageStatsByUser :one
SELECT
    COALESCE(SUM(tf.file_size), 0) as total_size_bytes,
    COALESCE(SUM(CASE WHEN tf.quality = 'source' THEN tf.file_size ELSE 0 END), 0) as source_size_bytes,
    COALESCE(SUM(CASE WHEN tf.quality = 'lossless' THEN tf.file_size ELSE 0 END), 0) as lossless_size_bytes,
    COALESCE(SUM(CASE WHEN tf.quality = 'lossy' THEN tf.file_size ELSE 0 END), 0) as lossy_size_bytes,
    COUNT(DISTINCT tf.id) as file_count,
    COUNT(DISTINCT t.project_id) as project_count,
    COUNT(DISTINCT t.id) as track_count
FROM track_files tf
INNER JOIN track_versions tv ON tf.version_id = tv.id
INNER JOIN tracks t ON tv.track_id = t.id
WHERE t.user_id = ?
`

type GetStorageStatsByUserRow struct {
	TotalSizeBytes    interface{} `json:"total_size_bytes"`
	SourceSizeBytes   interface{} `json:"source_size_bytes"`
	LosslessSizeBytes interface{} `json:"lossless_size_bytes"`
	LossySizeBytes    interface{} `json:"lossy_size_bytes"`
	FileCount         int64       `json:"file_count"`
	ProjectCount      int64       `json:"project_count"`
	TrackCount        int64       `json:"track_count"`
}

func (q *Queries) GetStorageStatsByUser(ctx context.Context, userID int64) (GetStorageStatsByUserRow, error) {
	row := q.db.QueryRowContext(ctx, getStorageStatsByUser, userID)
	var i GetStorageStatsByUserRow
	err := row.Scan(
		&i.TotalSizeBytes,
		&i.SourceSizeBytes,
		&i.LosslessSizeBytes,
		&i.LossySizeBytes,
		&i.FileCount,
		&i.ProjectCount,
		&i.TrackCount,
	)
	return i, err
}
