/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as ErrorRouteImport } from './routes/$error'
import { Route as ProfileRouteRouteImport } from './routes/profile/route'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as ResetSetupIndexRouteImport } from './routes/reset-setup/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as InitializeIndexRouteImport } from './routes/initialize/index'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as ShareTokenRouteImport } from './routes/share/$token'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as SharedTrackTrackIdRouteRouteImport } from './routes/shared-track.$trackId/route'
import { Route as ProjectProjectIdRouteRouteImport } from './routes/project.$projectId/route'
import { Route as SharedTrackTrackIdIndexRouteImport } from './routes/shared-track.$trackId/index'
import { Route as ProjectProjectIdIndexRouteImport } from './routes/project.$projectId/index'
import { Route as MainFolderFolderIdRouteRouteImport } from './routes/_main/folder.$folderId/route'
import { Route as MainFolderFolderIdIndexRouteImport } from './routes/_main/folder.$folderId/index'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/$error',
  path: '/$error',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRouteRoute = ProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetSetupIndexRoute = ResetSetupIndexRouteImport.update({
  id: '/reset-setup/',
  path: '/reset-setup/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const InitializeIndexRoute = InitializeIndexRouteImport.update({
  id: '/initialize/',
  path: '/initialize/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedTrackTrackIdRouteRoute = SharedTrackTrackIdRouteRouteImport.update({
  id: '/shared-track/$trackId',
  path: '/shared-track/$trackId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRouteRoute = ProjectProjectIdRouteRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedTrackTrackIdIndexRoute = SharedTrackTrackIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SharedTrackTrackIdRouteRoute,
} as any)
const ProjectProjectIdIndexRoute = ProjectProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectProjectIdRouteRoute,
} as any)
const MainFolderFolderIdRouteRoute = MainFolderFolderIdRouteRouteImport.update({
  id: '/folder/$folderId',
  path: '/folder/$folderId',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainFolderFolderIdIndexRoute = MainFolderFolderIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainFolderFolderIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/profile': typeof ProfileRouteRouteWithChildren
  '/$error': typeof ErrorRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/project/$projectId': typeof ProjectProjectIdRouteRouteWithChildren
  '/shared-track/$trackId': typeof SharedTrackTrackIdRouteRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/initialize/': typeof InitializeIndexRoute
  '/login/': typeof LoginIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/reset-setup/': typeof ResetSetupIndexRoute
  '/folder/$folderId': typeof MainFolderFolderIdRouteRouteWithChildren
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/shared-track/$trackId/': typeof SharedTrackTrackIdIndexRoute
  '/folder/$folderId/': typeof MainFolderFolderIdIndexRoute
}
export interface FileRoutesByTo {
  '/$error': typeof ErrorRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/invite/$token': typeof InviteTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/': typeof MainIndexRoute
  '/initialize': typeof InitializeIndexRoute
  '/login': typeof LoginIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/register': typeof RegisterIndexRoute
  '/reset-setup': typeof ResetSetupIndexRoute
  '/project/$projectId': typeof ProjectProjectIdIndexRoute
  '/shared-track/$trackId': typeof SharedTrackTrackIdIndexRoute
  '/folder/$folderId': typeof MainFolderFolderIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteRouteWithChildren
  '/profile': typeof ProfileRouteRouteWithChildren
  '/$error': typeof ErrorRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/project/$projectId': typeof ProjectProjectIdRouteRouteWithChildren
  '/shared-track/$trackId': typeof SharedTrackTrackIdRouteRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/_main/': typeof MainIndexRoute
  '/initialize/': typeof InitializeIndexRoute
  '/login/': typeof LoginIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/reset-setup/': typeof ResetSetupIndexRoute
  '/_main/folder/$folderId': typeof MainFolderFolderIdRouteRouteWithChildren
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/shared-track/$trackId/': typeof SharedTrackTrackIdIndexRoute
  '/_main/folder/$folderId/': typeof MainFolderFolderIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/$error'
    | '/accept-invite'
    | '/reset-password'
    | '/project/$projectId'
    | '/shared-track/$trackId'
    | '/invite/$token'
    | '/share/$token'
    | '/initialize/'
    | '/login/'
    | '/profile/'
    | '/register/'
    | '/reset-setup/'
    | '/folder/$folderId'
    | '/project/$projectId/'
    | '/shared-track/$trackId/'
    | '/folder/$folderId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$error'
    | '/accept-invite'
    | '/reset-password'
    | '/invite/$token'
    | '/share/$token'
    | '/'
    | '/initialize'
    | '/login'
    | '/profile'
    | '/register'
    | '/reset-setup'
    | '/project/$projectId'
    | '/shared-track/$trackId'
    | '/folder/$folderId'
  id:
    | '__root__'
    | '/_main'
    | '/profile'
    | '/$error'
    | '/accept-invite'
    | '/reset-password'
    | '/project/$projectId'
    | '/shared-track/$trackId'
    | '/invite/$token'
    | '/share/$token'
    | '/_main/'
    | '/initialize/'
    | '/login/'
    | '/profile/'
    | '/register/'
    | '/reset-setup/'
    | '/_main/folder/$folderId'
    | '/project/$projectId/'
    | '/shared-track/$trackId/'
    | '/_main/folder/$folderId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRouteRoute: typeof MainRouteRouteWithChildren
  ProfileRouteRoute: typeof ProfileRouteRouteWithChildren
  ErrorRoute: typeof ErrorRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ProjectProjectIdRouteRoute: typeof ProjectProjectIdRouteRouteWithChildren
  SharedTrackTrackIdRouteRoute: typeof SharedTrackTrackIdRouteRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
  ShareTokenRoute: typeof ShareTokenRoute
  InitializeIndexRoute: typeof InitializeIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  ResetSetupIndexRoute: typeof ResetSetupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$error': {
      id: '/$error'
      path: '/$error'
      fullPath: '/$error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-setup/': {
      id: '/reset-setup/'
      path: '/reset-setup'
      fullPath: '/reset-setup/'
      preLoaderRoute: typeof ResetSetupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initialize/': {
      id: '/initialize/'
      path: '/initialize'
      fullPath: '/initialize/'
      preLoaderRoute: typeof InitializeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared-track/$trackId': {
      id: '/shared-track/$trackId'
      path: '/shared-track/$trackId'
      fullPath: '/shared-track/$trackId'
      preLoaderRoute: typeof SharedTrackTrackIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared-track/$trackId/': {
      id: '/shared-track/$trackId/'
      path: '/'
      fullPath: '/shared-track/$trackId/'
      preLoaderRoute: typeof SharedTrackTrackIdIndexRouteImport
      parentRoute: typeof SharedTrackTrackIdRouteRoute
    }
    '/project/$projectId/': {
      id: '/project/$projectId/'
      path: '/'
      fullPath: '/project/$projectId/'
      preLoaderRoute: typeof ProjectProjectIdIndexRouteImport
      parentRoute: typeof ProjectProjectIdRouteRoute
    }
    '/_main/folder/$folderId': {
      id: '/_main/folder/$folderId'
      path: '/folder/$folderId'
      fullPath: '/folder/$folderId'
      preLoaderRoute: typeof MainFolderFolderIdRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/folder/$folderId/': {
      id: '/_main/folder/$folderId/'
      path: '/'
      fullPath: '/folder/$folderId/'
      preLoaderRoute: typeof MainFolderFolderIdIndexRouteImport
      parentRoute: typeof MainFolderFolderIdRouteRoute
    }
  }
}

interface MainFolderFolderIdRouteRouteChildren {
  MainFolderFolderIdIndexRoute: typeof MainFolderFolderIdIndexRoute
}

const MainFolderFolderIdRouteRouteChildren: MainFolderFolderIdRouteRouteChildren =
  {
    MainFolderFolderIdIndexRoute: MainFolderFolderIdIndexRoute,
  }

const MainFolderFolderIdRouteRouteWithChildren =
  MainFolderFolderIdRouteRoute._addFileChildren(
    MainFolderFolderIdRouteRouteChildren,
  )

interface MainRouteRouteChildren {
  MainIndexRoute: typeof MainIndexRoute
  MainFolderFolderIdRouteRoute: typeof MainFolderFolderIdRouteRouteWithChildren
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainIndexRoute: MainIndexRoute,
  MainFolderFolderIdRouteRoute: MainFolderFolderIdRouteRouteWithChildren,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

interface ProfileRouteRouteChildren {
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteRouteChildren: ProfileRouteRouteChildren = {
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteRouteWithChildren = ProfileRouteRoute._addFileChildren(
  ProfileRouteRouteChildren,
)

interface ProjectProjectIdRouteRouteChildren {
  ProjectProjectIdIndexRoute: typeof ProjectProjectIdIndexRoute
}

const ProjectProjectIdRouteRouteChildren: ProjectProjectIdRouteRouteChildren = {
  ProjectProjectIdIndexRoute: ProjectProjectIdIndexRoute,
}

const ProjectProjectIdRouteRouteWithChildren =
  ProjectProjectIdRouteRoute._addFileChildren(
    ProjectProjectIdRouteRouteChildren,
  )

interface SharedTrackTrackIdRouteRouteChildren {
  SharedTrackTrackIdIndexRoute: typeof SharedTrackTrackIdIndexRoute
}

const SharedTrackTrackIdRouteRouteChildren: SharedTrackTrackIdRouteRouteChildren =
  {
    SharedTrackTrackIdIndexRoute: SharedTrackTrackIdIndexRoute,
  }

const SharedTrackTrackIdRouteRouteWithChildren =
  SharedTrackTrackIdRouteRoute._addFileChildren(
    SharedTrackTrackIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  MainRouteRoute: MainRouteRouteWithChildren,
  ProfileRouteRoute: ProfileRouteRouteWithChildren,
  ErrorRoute: ErrorRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ProjectProjectIdRouteRoute: ProjectProjectIdRouteRouteWithChildren,
  SharedTrackTrackIdRouteRoute: SharedTrackTrackIdRouteRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
  ShareTokenRoute: ShareTokenRoute,
  InitializeIndexRoute: InitializeIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  ResetSetupIndexRoute: ResetSetupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
